Make docker:run use an internal docker-run command

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -22,7 +22,7 @@ jobs:
           printf "\n------------------------------------------------------\n"
           #------------------------
           bb stack:sync || exit 1
-          printf "------------------------------------------------------\n"
+          echo "------------------------------------------------------"
 
           # Bucket deletion
           printf "\n------------------------------------------------------\n"
@@ -30,7 +30,7 @@ jobs:
           printf "\n------------------------------------------------------\n"
           #------------------------
           bb stack:doctor || exit 1
-          printf "------------------------------------------------------\n"
+          echo "------------------------------------------------------"
 
           # Bucket creation
           printf "\n------------------------------------------------------\n"
@@ -39,7 +39,7 @@ jobs:
           #------------------------
           bb bucket:create || exit 1
           bb bucket:create :bucket-name hlhlnativetestzxcqwedsasd1
-          printf "------------------------------------------------------\n"
+          echo "------------------------------------------------------"
 
           # Bucket deletion
           printf "\n------------------------------------------------------\n"
@@ -48,7 +48,7 @@ jobs:
           #------------------------
           bb bucket:remove || exit 1
           bb bucket:remove :bucket-name hlhlnativetestzxcqwedsasd1
-          printf "------------------------------------------------------\n"
+          echo "------------------------------------------------------"
 
           # Stack version test
           printf "\n------------------------------------------------------\n"
@@ -56,7 +56,7 @@ jobs:
           printf "\n------------------------------------------------------\n"
           #------------------------
           bb stack:version || exit 1
-          printf "------------------------------------------------------\n"
+          echo "------------------------------------------------------"
 
           # Basic stack compilation
           printf "\n------------------------------------------------------\n"
@@ -64,31 +64,31 @@ jobs:
           printf "\n------------------------------------------------------\n"
           #------------------------
           bb stack:compile || exit 1
-          printf "------------------------------------------------------\n"
+          echo "------------------------------------------------------"
 
           # Basic stack pack
           printf "\n------------------------------------------------------\n"
-          printf "                  (8) Stack pack                          "
+          printf "            (8) Stack pack + RT overwrite                 "
           printf "\n------------------------------------------------------\n"
           #------------------------
-          bb stack:pack || exit 1
-          printf "------------------------------------------------------\n"
+          bb stack:pack :runtime :java || exit 1
+          echo "------------------------------------------------------"
 
           # Deploy stack dry
           printf "\n------------------------------------------------------\n"
-          printf "                  (9) Stack deploy dry                    "
+          printf "            (9) Stack deploy dry + RT overwrite          "
           printf "\n------------------------------------------------------\n"
           #------------------------
-          bb stack:deploy :dry || exit 1
-          printf "------------------------------------------------------\n"
+          bb stack:deploy :runtime :java :dry || exit 1
+          echo "------------------------------------------------------"
 
           # Deploy stack
           printf "\n------------------------------------------------------\n"
-          printf "                  (10) Stack deploy                       "
+          printf "             (10) Stack deploy + RT overwrite             "
           printf "\n------------------------------------------------------\n"
           #------------------------
-          bb stack:deploy || exit 1
-          printf "------------------------------------------------------\n"
+          bb stack:deploy :runtime :java || exit 1
+          echo "------------------------------------------------------"
 
           # Destroy stack
           printf "\n------------------------------------------------------\n"
@@ -96,7 +96,16 @@ jobs:
           printf "\n------------------------------------------------------\n"
           #------------------------
           bb stack:destroy || exit 1
-          printf "------------------------------------------------------\n"
+          echo "------------------------------------------------------"
+
+          # Stack purge test
+          printf "\n------------------------------------------------------\n"
+          printf "           (12) In docker:run in local context fail       "
+          printf "\n------------------------------------------------------\n"
+          #------------------------
+          HL_NO_DOCKER=true bb docker:run "something" && exit 1 || printf "\033[0;32mTest passed!\033[0m"
+          echo "------------------------------------------------------"
+
 
           # Stack purge test
           printf "\n------------------------------------------------------\n"
@@ -104,7 +113,8 @@ jobs:
           printf "\n------------------------------------------------------\n"
           #------------------------
           bb stack:purge || exit 1
-          printf "------------------------------------------------------\n"
+          echo "------------------------------------------------------"
+
 
         workingDirectory: ${{variables.WORKING_DIRECTORY}}
         displayName: 'Tasks health check'
