Test :force compilation

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -38,7 +38,7 @@ jobs:
           printf "\n------------------------------------------------------\n"
           #------------------------
           bb bucket:create || exit 1
-          bb bucket:create :bucket-name hlhlnativetestzxcqwedsasd1
+          bb bucket:create :bucket-name hlhlnativetestzxcqwedsasd1 || exit 1
           echo "------------------------------------------------------"
 
           # Bucket deletion
@@ -47,7 +47,7 @@ jobs:
           printf "\n------------------------------------------------------\n"
           #------------------------
           bb bucket:remove || exit 1
-          bb bucket:remove :bucket-name hlhlnativetestzxcqwedsasd1
+          bb bucket:remove :bucket-name hlhlnativetestzxcqwedsasd1 || exit 1
           echo "------------------------------------------------------"
 
           # Stack version test
@@ -66,9 +66,17 @@ jobs:
           bb stack:compile || exit 1
           echo "------------------------------------------------------"
 
+          # Basic stack compilation
+          printf "\n------------------------------------------------------\n"
+          printf "              (8) Stack compilation + Force               "
+          printf "\n------------------------------------------------------\n"
+          #------------------------
+          bb stack:compile :force || exit 1
+          echo "------------------------------------------------------"
+
           # Basic stack pack
           printf "\n------------------------------------------------------\n"
-          printf "            (8) Stack pack + RT overwrite                 "
+          printf "            (9) Stack pack + RT overwrite                 "
           printf "\n------------------------------------------------------\n"
           #------------------------
           bb stack:pack :runtime :java || exit 1
@@ -76,7 +84,7 @@ jobs:
 
           # Deploy stack dry
           printf "\n------------------------------------------------------\n"
-          printf "            (9) Stack deploy dry + RT overwrite          "
+          printf "            (10) Stack deploy dry + RT overwrite          "
           printf "\n------------------------------------------------------\n"
           #------------------------
           bb stack:deploy :runtime :java :dry || exit 1
@@ -84,37 +92,51 @@ jobs:
 
           # Deploy stack
           printf "\n------------------------------------------------------\n"
-          printf "             (10) Stack deploy + RT overwrite             "
+          printf "             (11) Stack deploy + RT overwrite             "
           printf "\n------------------------------------------------------\n"
           #------------------------
           bb stack:deploy :runtime :java || exit 1
           echo "------------------------------------------------------"
 
+          # Describe full stack
+          printf "\n------------------------------------------------------\n"
+          printf "                 (12) Stack describe                      "
+          printf "\n------------------------------------------------------\n"
+          #------------------------
+          bb stack:describe || exit 1
+          echo "------------------------------------------------------"
+
           # Destroy stack
           printf "\n------------------------------------------------------\n"
-          printf "                  (11) Stack destroy                      "
+          printf "                  (13) Stack destroy                      "
           printf "\n------------------------------------------------------\n"
           #------------------------
-          bb stack:destroy || exit 1
+          bb stack:destroy || printf "Not yet removed"
+          echo "------------------------------------------------------"
+
+          # Stack local run test
+          printf "\n------------------------------------------------------\n"
+          printf "           (14) In docker:run in local context fail       "
+          printf "\n------------------------------------------------------\n"
+          #------------------------
+          HL_NO_DOCKER=true bb docker:run "something" && exit 1 || printf "\033[0;32mTest passed!\033[0m\n"
           echo "------------------------------------------------------"
 
           # Stack purge test
           printf "\n------------------------------------------------------\n"
-          printf "           (12) In docker:run in local context fail       "
-          printf "\n------------------------------------------------------\n"
-          #------------------------
-          HL_NO_DOCKER=true bb docker:run "something" && exit 1 || printf "\033[0;32mTest passed!\033[0m"
-          echo "------------------------------------------------------"
-
-
-          # Stack purge test
-          printf "\n------------------------------------------------------\n"
-          printf "                 (12) Stack purge                         "
+          printf "                 (15) Stack purge                         "
           printf "\n------------------------------------------------------\n"
           #------------------------
           bb stack:purge || exit 1
           echo "------------------------------------------------------"
 
+          # Stack deletion confirmation
+          printf "\n------------------------------------------------------\n"
+          printf "                 (16) Stack removed check                 "
+          printf "\n------------------------------------------------------\n"
+          #------------------------
+          bb stack:describe && exit 1 || printf "\033[0;32mTest passed!\033[0m\n"
+          echo "------------------------------------------------------"
 
         workingDirectory: ${{variables.WORKING_DIRECTORY}}
         displayName: 'Tasks health check'
